language: cpp
compiler:
    - gcc
    - clang

branches:
    only:
        - master

before_install:
  - sudo bash -c "echo 'deb http://lgp203.free.fr/ubuntu quantal universe' >> /etc/apt/sources.list.d/lgp203.free.fr.source.list"
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update

install: 
    - sudo apt-get install --force-yes make premake4 g++-4.8
    - if [ "$CXX" == "g++" ]; then export CXX=g++-4.8; export g++=g++-4.8; fi

before_script: premake4 gmake

script: make && bin/TAG_TestD