language: cpp
compiler:
    - gcc
    - clang

branches:
    only:
        - master

before_install:
  - sudo bash -c "echo 'deb http://lgp203.free.fr/ubuntu quantal universe' >> /etc/apt/sources.list.d/lgp203.free.fr.source.list"
  - sudo apt-get update

install: sudo apt-get install --force-yes make premake4

before_script: premake4 gmake

script: make && bin/TAG_TestD