[package]
name = "tag"
version = "0.1.0"
authors = ["thecoshman <git@thecoshman.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
